version: '3.8'

services:
  # Inventory Management Application
  inventory-app:
    build: .
    container_name: inventory-management-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MANAGEMENT_METRICS_EXPORT_GRAPHITE_HOST=graphite
      - MANAGEMENT_METRICS_EXPORT_GRAPHITE_PORT=2003
    depends_on:
      - graphite
    networks:
      - devops-network
    restart: unless-stopped

  # Graphite for metrics collection
  graphite:
    image: graphiteapp/graphite-statsd:latest
    container_name: graphite
    ports:
      - "2003:2003"  # Carbon plaintext
      - "2004:2004"  # Carbon pickle
      - "8081:80"    # Graphite web interface
    volumes:
      - graphite-data:/opt/graphite/storage
    networks:
      - devops-network
    restart: unless-stopped

  # Grafana for monitoring dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - graphite
    networks:
      - devops-network
    restart: unless-stopped

  # Jenkins for CI/CD
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    ports:
      - "8082:8080"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--httpPort=8080
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops-network
    restart: unless-stopped

volumes:
  graphite-data:
  grafana-data:
  jenkins-data:

networks:
  devops-network:
    driver: bridge 